// UI
export const SET_UI_INIT = 'SET_UI_INIT';
export const SET_UI_SHOULDUSEDARKMODE = 'SET_UI_SHOULDUSEDARKMODE';

// Game
export const SET_GAME_INIT = 'SET_GAME_INIT';
export const SET_GAME_GRID = 'SET_GAME_GRID';
export const SET_GAME_PLAYER_TURN = 'SET_GAME_PLAYER_TURN';


// Player
export const SET_PLAYER_INIT = 'SET_PLAYER_INIT';
export const INCREMENT_PLAYER_SCORE = 'INCREMENT_PLAYER_SCORE';
export const INCREMENT_PLAYER_BLOCK_COUNT = 'INCREMENT_PLAYER_BLOCK_COUNT';

